cache:
    paths:
    - vendor/

before_script:
    - composer install

test:
    script:
        - phpunit --verbose --testsuite=unit
        - phpunit --verbose --testsuite=functional
    only:
        - master
        - develop