stages:
    - test
    - migrate
    - dump_database
    - deploy

before_script:
    - bash .ci/gitlab-ci.sh install

test_job:
    stage: test
    script:
        - bash .ci/gitlab-ci.sh script unit
        - bash .ci/gitlab-ci.sh script functional
        - bash .ci/gitlab-ci.sh script phpcs

migrate_job:
    stage: migrate
    script:
        - bash .ci/gitlab-ci.sh script functional

dump_database_job:
    stage: dump_database
    script:
        - bash .ci/dumper.sh
    only:
        - master

deploy_job:
    stage: deploy
    script:
        - bash .ci/deploy.sh
    only:
        - master
