cache:
    paths:
    - vendor/

before_script:
    - echo $PWD
    - bash .ci/gitlab-ci.sh install

test:
    script:
        - bash .ci/gitlab-ci.sh script

    only:
        - master
        - develop