stages:
    - migrate
    - test
    - deploy

before_script:
    - bash .ci/gitlab-ci.sh install

migrate_job:
    stage: migrate
    script:
        - bash .ci/gitlab-ci.sh script functional

test_job:
    stage: test
    script:
        - bash .ci/gitlab-ci.sh script unit
        - bash .ci/gitlab-ci.sh script functional
        - bash .ci/gitlab-ci.sh script phpcs

deploy_job:
    stage: deploy
    script:
        - bash .ci/deploy.sh
    only:
        - master
