sudo: false

language: php

branches:
    only:
        - master

services:
    - postgresql

php:
    - 7.0

before_script:
    - bash .ci/travis-ci.sh install
script:
    - bash .ci/travis-ci.sh script unit