sudo: false

language: php

cache:
    directories:
        - .autoconf
        - $HOME/.composer

branches:
    only:
        - master

services:
    - postgresql

php:
    - 7.0
    - 7.1

before_script:
    - bash .ci/travis-ci.sh install
script:
    - bash .ci/travis-ci.sh script unit
    - bash .ci/travis-ci.sh script functional
    - bash .ci/travis-ci.sh script phpcs
