parameters:
    user.ovpn.class:                Ovpn\Entity\Users
    user_manager.ovpn.class:        Ovpn\Model\UserManager
    proxy_container.class:          Kernel\ProxyContainer
    security_facade.class:          Ovpn\Security\SecurityFacade

services:
    container:
        class: %proxy_container.class%

    ovpn_user.entity:
        class: %user.ovpn.class%

    ovpn_user.manager:
        class: %user_manager.ovpn.class%
        arguments: ['@ovpn_user.entity']

    ovpn_security:
        class: %security_facade.class%