parameters:
    config.class:                   Ovpn\Core\Config
    user_manager.ovpn.class:        Ovpn\Model\UserManager
    user_repositiory.class:         Ovpn\Repository\UserRepository
    proxy_container.class:          Kernel\ProxyContainer
    security_facade.class:          Ovpn\Security\SecurityFacade
    token.storage.class:            Ovpn\Security\TokenStorage
    user.class:                     Ovpn\Entity\Users
    security.class:                 Ovpn\Security\Security
    authorization.class:            Ovpn\Security\Authorization
    mail.mailgun.class:             Ovpn\Tools\MailgunMailer



services:
    container:
        class: %proxy_container.class%

    ovpn_config:
        class: %config.class%

    ovpn_user:
        class: %user.class%

    ovpn_user.repository:
        class: %user_repositiory.class%

    ovpn_token.storage:
        class: %token.storage.class%

    ovpn_security.abstract:
        class: %security.class%
        arguments: ['@ovpn_user']

    ovpn_user.manager:
        class: %user_manager.ovpn.class%
        arguments: ['@ovpn_config', '@ovpn_mailer', '@ovpn_openvpn.facade']

    ovpn_authorization:
        class: %authorization.class%
        arguments: ['@ovpn_token.storage', '@ovpn_user.repository']

    ovpn_security:
        class: %security_facade.class%
        arguments: ['@ovpn_authorization', '@ovpn_security.abstract', '@ovpn_token.storage']

    ovpn_mailer:
        class: %mail.mailgun.class%
        arguments: ['@ovpn_config']

    ovpn_token.session:
        class: Ovpn\Security\TokenSession
        public: false
        tags:
            - { name: secure.token, priority: 1 }

    ovpn_token.cookie:
        class: Ovpn\Security\TokenCookie
        public: false
        tags:
            - { name: secure.token, priority: 2 }

    ovpn_openvpn.facade:
        class: Ovpn\Tools\Openvpn\OpenvpnFacade