parameters:
    config.class:                   Ovpn\Core\Config
    user_manager.ovpn.class:        Ovpn\Model\UserManager
    proxy_container.class:          Kernel\ProxyContainer
    security_facade.class:          Ovpn\Security\SecurityFacade

services:
    container:
        class: %proxy_container.class%

    ovpn_config:
        class: %config.class%

    ovpn_user.manager:
        class: %user_manager.ovpn.class%
        arguments: ['@ovpn_config']

    ovpn_security:
        class: %security_facade.class%