parameters:
    config.class:                   Okvpn\OkvpnBundle\Core\Config
    user_manager.ovpn.class:        Okvpn\OkvpnBundle\Model\UserManager
    user_repositiory.class:         Okvpn\OkvpnBundle\Repository\UserRepository
    proxy_container.class:          Okvpn\Bridge\Kohana\Proxy\ProxyContainer
    security_facade.class:          Okvpn\OkvpnBundle\Security\SecurityFacade
    token.storage.class:            Okvpn\OkvpnBundle\Security\TokenStorage
    user.class:                     Okvpn\OkvpnBundle\Entity\Users
    security.class:                 Okvpn\OkvpnBundle\Security\Security
    authorization.class:            Okvpn\OkvpnBundle\Security\Authorization
    mail.mailgun.class:             Okvpn\OkvpnBundle\Tools\MailgunMailer



services:
    container:
        class: 'Symfony\Component\DependencyInjection\Container'
        factory: ['Okvpn\Bridge\Kohana\Factory\ContainerCreater', create]

    event_dispatcher:
        class: 'Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher'
        arguments:
            - '@container'

    ovpn_recaptcha:
        class: 'Okvpn\OkvpnBundle\Tools\Recaptcha'
        arguments:
            - '@ovpn_config'

    ovpn_config:
        class: '%config.class%'

    ovpn_user:
        class: '%user.class%'

    ovpn_user.repository:
        class: '%user_repositiory.class%'

    ovpn_token.storage:
        class: '%token.storage.class%'

    ovpn_security.abstract:
        class: '%security.class%'
        arguments: ['@ovpn_user']

    ovpn_user.manager:
        class: '%user_manager.ovpn.class%'
        arguments:
            - '@event_dispatcher'
            - '@ovpn_config'
            - '@ovpn_mailer'
            - '@ovpn_openvpn.factory'
            - '@ovpn_user.repository'
            - '@ovpn_recaptcha'
            - '@ovpn_user.filter'

    ovpn_authorization:
        class: '%authorization.class%'
        arguments: ['@ovpn_token.storage', '@ovpn_user.repository']

    ovpn_security:
        class: '%security_facade.class%'
        arguments: ['@ovpn_authorization', '@ovpn_security.abstract', '@ovpn_token.storage']

    ovpn_mailer:
        class: 'Okvpn\OkvpnBundle\Tools\SwiftMailer'
        arguments: ['@ovpn_config']

    ovpn_token.session:
        class: 'Okvpn\OkvpnBundle\Security\TokenSession'
        public: false
        tags:
            - { name: secure.token, priority: 1 }

    ovpn_token.cookie:
        class: 'Okvpn\OkvpnBundle\Security\TokenCookie'
        public: false
        tags:
            - { name: secure.token, priority: 2 }

    ovpn_user.filter:
        class: 'Okvpn\OkvpnBundle\Filter\UserFilter'
        arguments:
            - '@ovpn_user.repository'
            - '@ovpn_recaptcha'

    ovpn_openvpn.config.builder:
        class: 'Okvpn\OkvpnBundle\Tools\Openvpn\ConfigBuilder'

    ovpn_openvpn.factory:
        class: 'Okvpn\OkvpnBundle\Tools\Openvpn\Config\ExtensionFactory'
        arguments:
            - '@ovpn_config'
            - '@ovpn_openvpn.config.builder'

    ovpn_create_user.event.listener:
        class: 'Okvpn\OkvpnBundle\EventListener\CreateUserEventListener'
        arguments:
            - '@ovpn_mailer'
            - '@ovpn_user.filter'
        tags:
            - { name: kernel.event_listener, event: pre.create_user, method: preCreateUser }
            - { name: kernel.event_listener, event: post.create_user, method: postCreateUser }
